name: Git SSH Checkout Buildkite Plugin
description: Exceptional functionality
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    repository-url:
      type: string
    ssh-secret-key-name:
      type: string
    checkout-path:
      type: string
  additionalProperties: false
